name: Update Fact

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: python fact.py

      - name: Inject into README
        run: |
          fact=$(cat FACT.md)
          awk '/<!-- FACT-START -->/{print;print fact;flag=1;next}/<!-- FACT-END -->/{flag=0} !flag' README.md > temp && mv temp README.md

      - name: Commit changes
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add README.md
          git commit -m "Updated fact" || exit 0
          git push
